// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgEMNhQu2_i67OFYhSNCuzb3MJ2V9jVlk',
    appId: '1:471623806269:web:20bb202d2052e5bbbee954',
    messagingSenderId: '471623806269',
    projectId: 'sheconomy-app',
    authDomain: 'sheconomy-app.firebaseapp.com',
    storageBucket: 'sheconomy-app.firebasestorage.app',
    measurementId: 'G-7V4FW68QEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD044huk3UkoCtUXR1vxCc7E0KuyiwrBJ0',
    appId: '1:471623806269:android:240fbe0d53051d62bee954',
    messagingSenderId: '471623806269',
    projectId: 'sheconomy-app',
    storageBucket: 'sheconomy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_TEUxookz1emkqu39ljIUBY_N2QDguPI',
    appId: '1:471623806269:ios:23f3ca55dbc098aebee954',
    messagingSenderId: '471623806269',
    projectId: 'sheconomy-app',
    storageBucket: 'sheconomy-app.firebasestorage.app',
    iosClientId: '471623806269-g4rlf2d4sc4a6d1tg40bv39qqi6ru0mc.apps.googleusercontent.com',
    iosBundleId: 'com.example.sheconomy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_TEUxookz1emkqu39ljIUBY_N2QDguPI',
    appId: '1:471623806269:ios:23f3ca55dbc098aebee954',
    messagingSenderId: '471623806269',
    projectId: 'sheconomy-app',
    storageBucket: 'sheconomy-app.firebasestorage.app',
    iosClientId: '471623806269-g4rlf2d4sc4a6d1tg40bv39qqi6ru0mc.apps.googleusercontent.com',
    iosBundleId: 'com.example.sheconomy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgEMNhQu2_i67OFYhSNCuzb3MJ2V9jVlk',
    appId: '1:471623806269:web:70285040f49d191bbee954',
    messagingSenderId: '471623806269',
    projectId: 'sheconomy-app',
    authDomain: 'sheconomy-app.firebaseapp.com',
    storageBucket: 'sheconomy-app.firebasestorage.app',
    measurementId: 'G-LK7EJNF9VN',
  );
}
